image: hashicorp/terraform:1.9.8

definitions:
  steps:
    - step: &tf_validate
        name: Terraform fmt & validate
        script:
          - terraform -version
          - terraform fmt -check -recursive -diff
          - terraform init -backend=false
          - terraform validate
    - step: &release
        name: Release (semantic-release)
        image: ghcr.io/adaptavist/docker-semantic-release:17.4.2-alpine3.11
        script:
          - semantic-release -r ${BITBUCKET_GIT_HTTP_ORIGIN}

pipelines:
  default:
    - step: *tf_validate

  branches:
    main:
      - step: *tf_validate
      - step: *release
